version: '3.8'

services:
  # ---------------------------------------------------
  # DATABASE
  # ---------------------------------------------------
  postgres:
    image: postgres:16-alpine
    container_name: supplychainx-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: supplychainx_db
      POSTGRES_USER: supplychainx_user
      POSTGRES_PASSWORD: supplychainx_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data     # Persist DB
    networks:
      - supplychainx-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U supplychainx_user -d supplychainx_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ---------------------------------------------------
  # SPRING BOOT APP
  # ---------------------------------------------------
  app:
    build: .
    container_name: supplychainx-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/supplychainx_db
      SPRING_DATASOURCE_USERNAME: supplychainx_user
      SPRING_DATASOURCE_PASSWORD: supplychainx_pass
    labels:
      - "co.elastic.logs/enabled=true"              # Enable Filebeat
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - supplychainx-network

  # ---------------------------------------------------
  # ELASTICSEARCH
  # ---------------------------------------------------
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
#    container_name: elasticsearch
#    environment:
#      - discovery.type=single-node                 # Dev mode
#      - xpack.security.enabled=false
#      - ES_JAVA_OPTS=-Xms512m -Xmx512m
#    ports:
#      - "9200:9200"
#    volumes:
#      - elasticsearch-data:/usr/share/elasticsearch/data
#    networks:
#      - supplychainx-network
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"  # قلل الذاكرة
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - supplychainx-network
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

  # ---------------------------------------------------
  # LOGSTASH
  # ---------------------------------------------------
  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.1
    container_name: logstash
    volumes:
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml:ro   # Root file
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    networks:
      - supplychainx-network
    depends_on:
      - elasticsearch

  # ---------------------------------------------------
  # KIBANA
  # ---------------------------------------------------
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - supplychainx-network
    depends_on:
      - elasticsearch

  # ---------------------------------------------------
  # FILEBEAT
  # ---------------------------------------------------
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.1
    container_name: filebeat
    user: root
    # ADD "-e" HERE. This enables logging to the console.
    command: [ "-e", "--strict.perms=false" ]
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - logstash
    networks:
      - supplychainx-network


volumes:
  postgres_data:
  elasticsearch-data:

networks:
  supplychainx-network:
    driver: bridge
